lane :store_dev do
  build_app(
    scheme: "SampleBitrise",
    output_name: "SampleBitrise.ipa", 
    export_method: "app-store",
    export_options: {
      silent: true,
      provisioningProfiles: { 
        "com.gooo-group.gooo.dev" => "Goo_DevStore",
      }
    }
  )
end