lane :store_prod do
  build_app(
    scheme: "Gooo",
    output_name: "Gooo.ipa", 
    export_method: "app-store",
    export_options: {
      silent: true,
      provisioningProfiles: { 
        "com.gooo-group.gooo" => "Goo Pro-Store",
      }
    }
  )
end

lane :store_dev do
  build_app(
    scheme: "Gooo-Dev",
    output_name: "Gooo-Dev.ipa", 
    export_method: "app-store",
    export_options: {
      silent: true,
      provisioningProfiles: { 
        "com.gooo-group.gooo.dev" => "Goo_DevStore",
      }
    }
  )
end

lane :upload_sentry do
  sentry_upload_dif(
    auth_token: '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',
    org_slug: 'freelance-2m',
    project_slug: 'gooo',
    include_sources: true
  )
end

lane :upload_sentry_dev do
  sentry_upload_dif(
    auth_token: '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',
    org_slug: 'freelance-2m',
    project_slug: 'gooo-dev',
    include_sources: true
  )
end